Repository lyra-j/uuno, pull requests merged in 2025-04, with the labels that each got.

#8 [FEAT]#7 login 구현
  middleware.ts
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/components/auth/AuthForm.tsx
  src/constants/messages.ts
  src/constants/path.ts
  src/constants/tables.ts
  src/services/auth.dto.ts
  src/types/auth.type.ts
  src/utils/supabase/client.ts
  src/utils/supabase/server.ts
  src/utils/validate-schema.ts
  tsconfig.json
Labels: 📬 API, ✨Feature

#13 [CHORE]#11 Supabase 패키지 추가 및 타입 정의 추가
  package.json
  pnpm-lock.yaml
  src/types/helpers.ts
  src/types/supabase.ts
  src/utils/supabase/middleware.ts
Labels: 🌐 Chore

#14 [FEAT]#9 social login 구현
  src/app/auth/callback/route.ts
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/auth/AuthForm.tsx
  src/components/auth/auth-form.tsx
  src/constants/messages.ts
  src/constants/tables.ts
  src/providers/tq-provider.tsx
  src/services/auth.dto.ts
  src/services/common.dto.ts
  src/services/social.dto.ts
  src/services/user.dto.ts
  src/types/supabase.type.ts
  src/utils/duplicate-validation.ts
  src/utils/supabase/client.ts
  src/utils/supabase/server.ts
  src/utils/validate-schema.ts
Labels: 📬 API, ✨Feature

#23 Chore/#12 css setting
  public/fonts/GeistMonoVF.woff
  public/fonts/GeistVF.woff
  public/fonts/pretendard/Pretendard-Bold.woff2
  public/fonts/pretendard/Pretendard-Medium.woff2
  public/fonts/pretendard/Pretendard-Regular.woff2
  src/app/globals.css
  tailwind.config.ts
Labels: 🌐 Chore

#24 [FEAT]#20 zustand 유저상태
  package.json
  pnpm-lock.yaml
  src/app/auth/callback/route.ts
  src/components/auth/auth-form.tsx
  src/components/layouts/Header.tsx
  src/services/auth.server.dto.ts
  src/services/common.server.dto.ts
  src/services/social.server.dto.ts
  src/services/user.server.dto.ts
  src/store/auth.store.ts
  src/utils/duplicate-validation.ts
Labels: 🌐 Chore, ✨Feature, 🫠 지수

#31 [FEAT]#30 konva 초기 파일 설치
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/main-card.png
  src/app/editer/page.tsx
  src/components/editer/CanvasEditor.tsx
  tailwind.config.ts
Labels: 🌐 Chore

#27 [REFACTOR]#25 로그인 회원가입
  src/app/auth/callback/route.ts
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/layout.tsx
  src/components/auth/auth-form.tsx
  src/components/auth/auth-listener.tsx
  src/components/layouts/header-auth-button.tsx
  src/components/layouts/header.tsx
  src/components/modals/auth/auth-login.tsx
  src/components/modals/auth/auth-modal.tsx
  src/components/modals/auth/auth-signup-email.tsx
  src/components/modals/auth/auth-signup.tsx
  src/constants/messages.ts
  src/services/auth.server.dto.ts
  src/services/user.client.dto.ts
  src/services/user.server.dto.ts
  src/store/modal.store.ts
  src/utils/auth/auth-check.ts
  src/utils/auth/duplicate-validation.ts
  src/utils/auth/validate-schema.ts
Labels: ♻️ Refactor, 🫠 지수

#41 [FEAT]#36 에디터 기본 UI 구현
  src/app/auth/callback/route.ts
  src/app/editer/page.tsx
  src/app/editor/page.tsx
  src/app/layout.tsx
  src/components/auth/auth-form.tsx
  src/components/editer/CanvasEditor.tsx
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/bottomTab/editor-bottom-tab.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/elements/backgrounds/elements-backgrounds.tsx
  src/components/editor/elements/diagrams/elements-diagrams.tsx
  src/components/editor/elements/pictures/elements-pictures.tsx
  src/components/editor/elements/qr-social/elements-social.tsx
  src/components/editor/elements/templates/elements-templates.tsx
  src/components/editor/elements/uploads/elements-uploads.tsx
  src/components/layouts/header-auth-button.tsx
  src/constants/auth.messages.constant.ts
  src/constants/editor.constant.ts
  src/constants/path.constant.ts
  src/constants/path.ts
  src/constants/tables.constant.ts
  src/services/auth.server.dto.ts
  src/services/common.server.dto.ts
  src/services/social.server.dto.ts
  src/services/user.client.dto.ts
  src/services/user.server.dto.ts
  src/store/editor.sidebar.store.ts
  src/utils/auth/duplicate-validation.ts
  src/utils/auth/validate-schema.ts
Labels: ✨Feature, 💄 Html&css, 🫠 지수

#46 [FEAT]#30 텍스트 에디터 구현
  package.json
  pnpm-lock.yaml
  src/app/editor/page.tsx
  src/app/layout.tsx
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/elements/text/text-canvas-stage.tsx
  src/components/editor/elements/text/text-edit-content.tsx
  src/components/editor/elements/text/text-editor.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/layouts/header.tsx
  src/store/editor.store.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#47 [FEAT] #42 디바운싱 함수 구현
  src/utils/common/common.debounce.utils.ts
Labels: ✨Feature, 🫠 지수

#52 [FEAT]#38 명함 상세 페이지 마크업
  src/app/card/[...id]/page.tsx
  src/components/card-detail/path-analysis-chart.tsx
  src/components/card-detail/path-analysis-grid.tsx
  src/components/card-detail/stat-card-grid.tsx
  src/components/card-detail/stat-card.tsx
  src/components/card-detail/weekly-chart.tsx
  src/components/card/flip-card.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 💄 Html&css, 🌸 수민

#53 Feat/#34 template list
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/icons/add.svg
  src/app/template-list/page.tsx
  src/components/icons/add-icon.tsx
  src/components/template-list/interactive-template-list.tsx
  src/components/template-list/style-select-button.tsx
  src/components/template-list/template-card.tsx
  src/components/template-list/template-preview-modal.tsx
  src/components/template-list/template-style-section.tsx
  src/components/ui/dialog.tsx
  src/types/supabase.ts
  src/types/supabase.type.ts
Labels: ✨Feature, 💄 Html&css, 🐳 미경

#49 [Feat]/#48 에디터 텍스트 관련 리펙토링
  package.json
  pnpm-lock.yaml
  src/app/editor/page.tsx
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/elements/text/text-canvas-stage.tsx
  src/components/editor/elements/text/text-edit-content.tsx
  src/components/editor/elements/text/text-editor.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/lib/editor/text/setup-textarea-styles.ts
Labels: ♻️ Refactor, ❤️ 종욱

#58 [FEAT]#48 에디터관련 리팩토링 및 툴바(삭제)
  src/app/editor/page.tsx
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/elements/text/text-canvas-stage.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/text/text-style-pannel.tsx
  src/store/editor.store.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#57 [FEAT]#54 명함 통계 월간 저장 수 및 주간 통계 그래프 추가
  package.json
  pnpm-lock.yaml
  src/apis/card-view.api.ts
  src/apis/interaction-line-chart.api.ts
  src/app/card/[...id]/page.tsx
  src/components/card-detail/path-analysis-grid.tsx
  src/components/card-detail/stat-card-grid.tsx
  src/components/card-detail/stat-card.tsx
  src/components/card-detail/weekly-chart.tsx
  src/components/chart/line-chart.tsx
  src/components/icons/change-down.tsx
  src/components/icons/change-none.tsx
  src/components/icons/change-up.tsx
  src/constants/date-format.constant.ts
  src/constants/query-key.ts
  src/constants/tables.constant.ts
  src/hooks/queries/use-month-save-cnt.ts
  src/hooks/queries/use-week-chart.ts
  src/utils/card-detail/month-range.util.ts
  src/utils/card-detail/week-range.util.ts
Labels: ✨Feature, 🌸 수민

#66 [CHORE] #65 iconify 라이브러리 설치
  package.json
  pnpm-lock.yaml
Labels: 🌐 Chore, 🐳 미경

#69 [FEAT]#63 명함 상세 페이지 도넛 통계 차트 추가
  src/apis/user-click-donut-chart.api.ts
  src/app/card/[...id]/page.tsx
  src/components/card-detail/path-analysis-chart.tsx
  src/components/card/flip-card.tsx
  src/components/chart/chart-wrapper.tsx
  src/components/chart/donut-chart.tsx
  src/constants/query-key.ts
  src/hooks/queries/use-click-total-chart.ts
Labels: ✨Feature, 🌸 수민

#72 [FEAT]#63 명함 상세 페이지 로직 개선
  src/apis/interaction-line-chart.api.ts
  src/app/card/[...id]/page.tsx
  src/components/card-detail/path-analysis-chart.tsx
  src/components/card-detail/path-analysis-grid.tsx
  src/components/card-detail/stat-card-grid.tsx
  src/components/card-detail/stat-card.tsx
  src/components/card-detail/weekly-chart.tsx
  src/components/card/flip-card.tsx
  src/components/chart/chart-wrapper.tsx
  src/components/chart/donut-chart.tsx
  src/components/chart/line-chart.tsx
  src/components/icons/csv-icon.tsx
  src/components/icons/flip-arrow.tsx
  src/components/icons/pdf-icon.tsx
  src/constants/tables.constant.ts
  src/types/supabase.ts
  src/utils/card-detail/month-range.util.ts
  src/utils/card-detail/week-range.util.ts
Labels: ✨Feature, ♻️ Refactor, 🌸 수민

#73 [REFACTOR] #56 헤더 수정 및 버튼 공통컴포넌트 추가
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/components/common/common-button.tsx
  src/components/layouts/header-auth-button.tsx
  src/components/layouts/header.tsx
  src/components/layouts/nav-bar.tsx
  src/components/ui/dropdown-menu.tsx
  src/constants/path.constant.ts
Labels: ♻️ Refactor, 🐳 미경

#75 [STYLE]#71 공유된 명함 페이지 마크업
  middleware.ts
  src/app/[...slug]/page.tsx
  src/app/card/[...id]/page.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/card/flip-card.tsx
Labels: 💄 Html&css, 🌸 수민

#77 [FEAT]#68 명함 선택 목록 추가 및 CSV/PDF 버튼 비활성화 조건문 추가
  public/icons/triangle.svg
  src/apis/card-select-list.ts
  src/app/card/[...id]/page.tsx
  src/components/auth/auth-form.tsx
  src/components/card-detail/card-selector.tsx
  src/components/card-detail/export-buttons.tsx
  src/components/card-detail/stat-card-grid.tsx
  src/components/card-detail/weekly-chart.tsx
  src/components/chart/donut-chart.tsx
  src/components/icons/csv-disable-icon.tsx
  src/components/icons/left-arrow.tsx
  src/components/icons/pdf-disable-icon.tsx
  src/constants/query-key.ts
  src/constants/tables.constant.ts
  src/hooks/queries/use-card-select-list.ts
  src/store/auth.store.ts
  src/store/card-data.store.ts
Labels: ✨Feature, 🌸 수민

#83 [REFACTOR]#80 사이드 바 리팩토링
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar.tsx
  src/store/editor.store.ts
  src/utils/editor/editor-engtokor.util.ts
Labels: ♻️ Refactor, 🫠 지수

#76 [FEAT}/#70 에디터 업로드 이미지 추가 및 조절
  src/app/editor/page.tsx
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/elements/images/elements-images.tsx
  src/components/editor/elements/pictures/elements-pictures.tsx
  src/components/editor/elements/text/element-text-canvas.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/text/text-style-panel.tsx
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/components/editor/elements/uploads/elements-uploads.tsx
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/constants/editor.constant.ts
  src/store/editor.store.ts
  src/utils/editor/editor-engtokor.util.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#78 [REFACTOR] #55 템플릿 리스트 탭 뷰 형식으로 변경
  src/apis/template-list.api.ts
  src/app/template-list/(style)/simple/page.tsx
  src/app/template-list/(style)/trendy/page.tsx
  src/app/template-list/layout.tsx
  src/app/template-list/page.tsx
  src/components/layouts/nav-bar.tsx
  src/components/template-list/interactive-template-list.tsx
  src/components/template-list/style-select-button.tsx
  src/components/template-list/tab-buttons.tsx
  src/components/template-list/template-card.tsx
  src/components/template-list/template-style-section.tsx
  src/constants/path.constant.ts
  src/constants/template.constant.ts
Labels: ♻️ Refactor, 🐳 미경

#85 [FEAT]/#79 에디터 sidebar & 캔버스 배경 색 변경
  package.json
  pnpm-lock.yaml
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/elements/backgrounds/background-sidebar.tsx
  src/components/editor/elements/backgrounds/elements-backgrounds.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/store/editor.store.ts
  src/utils/editor/editor-engtokor.util.ts
Labels: ✨Feature, ❤️ 종욱

#86 [FEAT]#74 명함 인터렉션 히트맵
  src/apis/card-interaction.ts
  src/apis/card-social-list.ts
  src/apis/interaction.ts
  src/app/api/log-exit/route.ts
  src/components/card/flip-card.tsx
  src/constants/query-key.ts
  src/constants/tables.constant.ts
  src/hooks/mutations/use-init-session.ts
  src/hooks/queries/use-card-interaction.ts
  src/hooks/queries/use-card-social-list.ts
  src/hooks/queries/use-ip-address.ts
  src/hooks/use-interaction-tracker.ts
  src/types/supabase.ts
  src/utils/interaction/format-date.ts
  src/utils/interaction/session-util.ts
Labels: ✨Feature, 🌸 수민

#87 [REFACTOR] #62 undo redo refactoring
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/store/editor.store.ts
Labels: ✨Feature, ♻️ Refactor, 🫠 지수

#88 FEAT/#82 텍스트 속성 사이드바를 분리
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/text/text-style-sidebar.tsx
  src/components/layouts/nav-bar.tsx
  src/components/main/section-four.tsx
  src/components/main/section-one.tsx
  src/components/main/section-two.tsx
Labels: ♻️ Refactor, ❤️ 종욱

#90 Feat/#84 에디터 툴바 위치 조절 및 요소 복사 로직 추가
  src/components/editor/editor-canvas.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/elements/images/elements-images.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/components/icons/editor/toolbar-delete.tsx
  src/components/icons/editor/toolbar-duplicate.tsx
  src/constants/editor.constant.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#94 [FEAT]#89 공통 모달 추가 및 저장 및 공유하기 모달 마크업
  public/icons/img-save.svg
  public/icons/kakao-share.svg
  public/icons/qr-copy.svg
  public/icons/tag-copy.svg
  src/app/card/[...id]/page.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/card/save-share-icon-item.tsx
  src/components/card/save-share-modal.tsx
  src/components/chart/line-chart.tsx
  src/components/common/common-modal.tsx
  src/store/common-modal.store.ts
Labels: 💄 Html&css, 🌸 수민

#100 [FEAT]#98 선택한 명함 데이터 페칭 및 버튼 활성화
  package.json
  pnpm-lock.yaml
  public/icons/warning.svg
  src/apis/get-slug-data.ts
  src/app/card/[...id]/page.tsx
  src/components/card-detail/card-selector.tsx
  src/components/card-detail/left-nav-section.tsx
  src/utils/card-detail/custom-sweet-alert.ts
  src/utils/common/sweet-alert-util.ts
Labels: ✨Feature, 💄 Html&css, 🌸 수민

#109 FEAT/#96 에디터 QR 부분 추가
  package.json
  pnpm-lock.yaml
  src/app/editor/page.tsx
  src/components/common/switch-case.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/qr-social/element-qr-canvas.tsx
  src/components/editor/elements/qr-social/elements-social.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/constants/editor.constant.ts
  src/store/editor.store.ts
  src/utils/editor/editor-engtokor.util.ts
Labels: ✨Feature, ❤️ 종욱

#115 [FEAT]#110 editor UI svg
  src/components/icons/editor/sidebar-background.tsx
  src/components/icons/editor/sidebar-element.tsx
  src/components/icons/editor/sidebar-image.tsx
  src/components/icons/editor/sidebar-social.tsx
  src/components/icons/editor/sidebar-template.tsx
  src/components/icons/editor/sidebar-text.tsx
  src/components/icons/editor/sidebar-toggle-left.tsx
  src/components/icons/editor/sidebar-toggle-right.tsx
  src/components/icons/editor/sidebar-upload.tsx
  src/components/icons/editor/topbar-minus.tsx
  src/components/icons/editor/topbar-plus.tsx
  src/components/icons/editor/topbar-redo.tsx
  src/components/icons/editor/topbar-reset.tsx
  src/components/icons/editor/topbar-switch.tsx
  src/components/icons/editor/topbar-undo.tsx
Labels: 💄 Html&css, 🫠 지수

#103 Feat/#92 dashboard mycardlist
  middleware.ts
  src/apis/dashboard.api.ts
  src/app/dashboard/account/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/my-cards/page.tsx
  src/app/dashboard/page.tsx
  src/components/common/common-input.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/dashboard/card-item.tsx
  src/components/dashboard/card-title-editor.tsx
  src/components/dashboard/create-new-card.tsx
  src/components/dashboard/dashboard-tab.tsx
  src/components/dashboard/sort-dropdown.tsx
  src/components/icons/delete-icon.tsx
  src/components/icons/more-menu-icon.tsx
  src/components/icons/pencil-icon.tsx
  src/components/icons/preview-icon.tsx
  src/components/layouts/nav-bar.tsx
  src/constants/path.constant.ts
Labels: ✨Feature, 💄 Html&css, 🐳 미경

#116 [FEAT]#112 editor UI
  src/components/editor/editor-ui/bottomTab/editor-bottom-tab.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar.tsx
  src/constants/editor.constant.ts
Labels: 💄 Html&css, 🫠 지수

#113 [FEAT]#45 zoom, reset
  src/app/editor/page.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/constants/editor.constant.ts
  src/store/editor.sidebar.store.ts
  src/store/editor.store.ts
  src/utils/editor/editor-scale-event.util.ts
Labels: ✨Feature, 🫠 지수

#118 [FEAT] #104 캔버스 앞면 뒷면 변경
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/bottomTab/editor-bottom-tab.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/store/editor.store.ts
  src/utils/editor/editor-getCanvasKeys.util.ts
Labels: ✨Feature, ♻️ Refactor, 🫠 지수

#119 [FEAT]#97 명함 상세 저장 및 공유하기
  src/apis/interaction.ts
  src/app/layout.tsx
  src/components/auth/auth-form.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/card/kakao-script.tsx
  src/components/card/save-share-modal.tsx
  src/components/dashboard/card-item.tsx
  src/constants/card-image.ts
  src/hooks/mutations/use-init-session.ts
  src/hooks/use-Image-downloader.ts
  src/hooks/use-interaction-tracker.ts
  src/hooks/use-vcard-saver.ts
  src/store/auth.store.ts
Labels: ✨Feature, 🌸 수민

#122 [FEAT]/#117 에디터 내용 저장
  src/apis/card-save.ts
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/hooks/mutations/use-card-save.ts
  src/store/editor.store.ts
  src/types/supabase.ts
  src/utils/editor/editor-cal-toolbar-position.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#133 Feat/#124 에디터에서 발생한 문제점들 수정
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/bottomTab/editor-bottom-tab.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/text/element-text-canvas.tsx
  src/components/editor/elements/text/text-edit-content.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/components/icons/editor/sidebar-upload.tsx
  src/components/icons/preview-icon.tsx
  src/constants/editor.constant.ts
  src/store/editor.store.ts
  src/utils/editor/editor-calculate-toolbar-position.ts
  src/utils/editor/editor-engtokor.util.ts
Labels: ♻️ Refactor, ❤️ 종욱

#128 [FEAT]#108 대시보드 월간통계 추가
  public/minichart.png
  src/apis/monthly-chart.api.ts
  src/app/dashboard/my-cards/page.tsx
  src/components/dashboard/monthly-chart.tsx
  src/components/dashboard/monthly-line-chart.tsx
  src/components/dashboard/most-view-card.tsx
  src/constants/query-key.ts
  src/hooks/queries/use-month-chart.ts
  src/utils/card-detail/month-range.util.ts
  src/utils/interaction/format-date.ts
Labels: ✨Feature, 🐳 미경

#143 [CHORE]#136 타이포그래피 줄간격 변경 반영
  src/config/tailwind.typography.ts
Labels: 🌐 Chore, 🐳 미경

#142 [REFACTOR]/#101 에디터 텍스트 수정 및 부분 추가
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/elements/backgrounds/background-sidebar.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/text/text-style-sidebar.tsx
  src/components/icons/editor/link-icon.tsx
  src/components/icons/editor/text-bold-icon.tsx
  src/components/icons/editor/text-italic-icon.tsx
  src/components/icons/editor/text-minus-size.tsx
  src/components/icons/editor/text-plus-size.tsx
  src/components/icons/editor/text-strike-icon.tsx
  src/components/icons/editor/text-underline-icon.tsx
  src/store/editor.store.ts
Labels: ♻️ Refactor, ❤️ 종욱

#131 [FEAT]#120 소셜 링크 추가
  public/icons/github.svg
  public/icons/instagram.svg
  public/icons/kakaotalk.svg
  public/icons/linkedin.svg
  public/icons/notion.svg
  public/icons/youtube.svg
  src/components/editor/editor-container.tsx
  src/components/editor/elements/qr-social/element-social-canvas.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/constants/editor.constant.ts
  src/store/editor.sidebar.store.ts
  src/store/editor.store.ts
Labels: ✨Feature, 💄 Html&css, 🫠 지수

#134 [FEAT]#127 명함 상세페이지 마크업 및 기능 수정
  public/icons/triangle.svg
  src/app/card/[...id]/page.tsx
  src/components/card-detail/card-selector.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/card-detail/left-nav-skeleton-ui.tsx
  src/components/card-detail/path-analysis-chart.tsx
  src/components/card-detail/stat-card.tsx
  src/components/card-detail/weekly-chart.tsx
  src/components/card/flip-card.tsx
  src/components/chart/chart-wrapper.tsx
  src/components/chart/line-chart.tsx
Labels: ✨Feature, 💄 Html&css, 🌸 수민

#137 [FEAT]#135 내 명함 통계 방문자 클릭 분석
  src/apis/user-click-donut-chart.api.ts
  src/components/chart/donut-chart.tsx
  src/config/tailwind.colors.ts
Labels: ✨Feature, 🌸 수민

#141 [FEAT] #129 명함 상세페이지 월간 조회 구현
  src/apis/card-view.api.ts
  src/components/card-detail/stat-card-grid.tsx
  src/components/dashboard/monthly-line-chart.tsx
  src/constants/query-key.ts
  src/hooks/queries/use-month-view-cnt.ts
Labels: ✨Feature, 🐳 미경

#150 [FEAT]/#132 에디터 템플릿 사이드바 및 로직
  src/apis/template-list.client.api.ts
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/elements/templates/elements-templates.tsx
  src/components/editor/elements/templates/templates-sidebar.tsx
  src/constants/query-key.ts
  src/hooks/queries/use-template-list.ts
  src/store/editor.store.ts
Labels: ✨Feature, ❤️ 종욱

#153 [FEAT]#152 공유된 명함 페이지 명함 데이터 페칭
  src/apis/interaction.ts
  src/components/card/card-skeleton.tsx
  src/components/card/error-card.tsx
  src/components/card/flip-card.tsx
  src/constants/query-key.ts
  src/constants/tables.constant.ts
  src/hooks/queries/use-card-interaction.ts
Labels: ✨Feature, 🌸 수민

#154 [FEAT]#149 에디터 업로드 화면 마크업
  public/icons/delete.svg
  public/icons/info.svg
  public/icons/upload.svg
  src/components/editor/elements/uploads/uploads-sidebar.tsx
Labels: 💄 Html&css, 🌸 수민

#146 [FEAT] #145 select horizon verticle UI
  src/app/editor/page.tsx
  src/components/editor/modal/editor-vt-hr-select-modal.tsx
  src/components/icons/editor/canvas-horizon.tsx
  src/components/icons/editor/canvas-vericle.tsx
Labels: 💄 Html&css, 🫠 지수

#155 [FEAT] #139 qr social UI
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
Labels: ♻️ Refactor, 💄 Html&css, 🫠 지수

#156 FEAT/#101 에디터 텍스트 속성 추가 및 UI 변경 및 저장시 반영 및 앞뒷면 구분 변경
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/elements/text/element-text-canvas.tsx
  src/components/editor/elements/text/text-edit-content.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/text/text-style-sidebar.tsx
  src/components/icons/editor/text/text-add.tsx
  src/components/icons/editor/text/text-align-bottom.tsx
  src/components/icons/editor/text/text-align-top.tsx
  src/components/icons/editor/text/text-align-vertical.tsx
  src/components/icons/editor/text/text-bold-icon.tsx
  src/components/icons/editor/text/text-italic-icon.tsx
  src/components/icons/editor/text/text-line-height-icon.tsx
  src/components/icons/editor/text/text-minus-size.tsx
  src/components/icons/editor/text/text-plus-size.tsx
  src/components/icons/editor/text/text-state-align-both.tsx
  src/components/icons/editor/text/text-state-align-center.tsx
  src/components/icons/editor/text/text-state-align-left.tsx
  src/components/icons/editor/text/text-state-align-right.tsx
  src/components/icons/editor/text/text-strike-icon.tsx
  src/components/icons/editor/text/text-underline-icon.tsx
  src/store/editor.store.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#151 [FEAT]#105 수직 수평 선택
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/modal/editor-vt-hr-select-modal.tsx
  src/constants/editor.constant.ts
  src/store/editor.sidebar.store.ts
  src/store/editor.store.ts
  src/types/supabase.ts
  src/utils/editor/warn-sweet-alert.ts
Labels: ✨Feature, ♻️ Refactor, 🫠 지수

#163 FEAT/#158 공유페이지 stage 생성 및 데이터 보여주기
  src/apis/interaction.ts
  src/components/card/flip-card.tsx
  src/components/card/konva-stage-viewer.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/elements/images/element-image-canvas.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/qr-social/element-qr-canvas.tsx
  src/components/editor/elements/qr-social/element-social-canvas.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/templates/templates-sidebar.tsx
  src/components/editor/elements/text/element-text-canvas.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/text/text-style-sidebar.tsx
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/store/editor.store.ts
  src/types/editor.type.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#164 [FEAT]#123 명함 에디터 이미지 업로드 로직 추가
  src/apis/storage.ts
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/constants/query-key.ts
  src/constants/tables.constant.ts
  src/hooks/mutations/use-storage.ts
  src/hooks/queries/use-storage.ts
Labels: ✨Feature, 🌸 수민

#159 [REFACTOR] #147 대시보드 내명함 페이지 개선
  middleware.ts
  src/app/template-list/layout.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/dashboard/card-item.tsx
  src/components/icons/more-menu-icon.tsx
  src/components/icons/preview-icon.tsx
  src/components/layouts/nav-bar.tsx
  src/components/template-list/template-card.tsx
  src/components/template-list/template-preview-modal.tsx
  src/utils/interaction/format-date.ts
Labels: ♻️ Refactor, 🐳 미경

#161 [FEAT]#140 login auth UI
  src/components/auth/auth-form.tsx
  src/components/icons/auth/auth-confirm.tsx
  src/components/icons/auth/auth-error.tsx
  src/components/icons/auth/auth-google.tsx
  src/components/icons/auth/auth-kakao.tsx
  src/components/icons/auth/auth-mail.tsx
  src/components/icons/auth/auth-x-button.tsx
  src/components/modals/auth/auth-modal.tsx
  src/components/modals/auth/auth-signup.tsx
Labels: 💄 Html&css, 🫠 지수

#165 [FEAT] #162 바텀 탭 UI 추가
  src/components/editor/editor-ui/bottomTab/editor-bottom-tab.tsx
  src/components/icons/editor/bottomtab-down.tsx
  src/components/icons/editor/bottomtab-polygon.tsx
  src/components/icons/editor/bottomtab-up.tsx
Labels: ✨Feature, 💄 Html&css, 🫠 지수

#168 [FEAT] 월간 평균 듀레이션 통계 #166
  src/apis/monthly-duration.ts
  src/components/card-detail/stat-card-grid.tsx
  src/components/card-detail/stat-card.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/layouts/nav-bar.tsx
  src/constants/query-key.ts
  src/hooks/queries/use-month-avg-duration.ts
  src/utils/interaction/format-time.ts
Labels: ✨Feature, 🐳 미경

#171 Refactor/#170 template editor
  src/components/template-list/template-card.tsx
Labels: ♻️ Refactor, 🐳 미경

#172 [FEAT]#167 명함상세 페이지 명함플립 이미지 추가 및 공유된 명함 인터렉션
  src/apis/card-social-list.ts
  src/apis/interaction.ts
  src/components/card-detail/left-nav-section.tsx
  src/components/card/card-skeleton.tsx
  src/components/card/error-card.tsx
  src/components/card/flip-card.tsx
  src/components/card/konva-stage-viewer.tsx
  src/components/editor/elements/qr-social/element-social-canvas.tsx
  src/hooks/queries/use-card-interaction.ts
  src/hooks/queries/use-card-slug.ts
  src/hooks/queries/use-card-social-list.ts
  src/hooks/use-interaction-tracker.ts
  src/types/cards.type.ts
Labels: ✨Feature, 🌸 수민

#175 📄 docs : 리드미 셋팅 #174
  README.md
Labels: 📃 Docs, 🐳 미경, 🛸 Deploy

#179 [FEAT]#178 소셜 클릭 핸들러를 FlipCard 뒷면 컴포넌트도 추가
  src/components/card/flip-card.tsx
Labels: ✨Feature, 🌸 수민

#185 [CHORE]#184 sentry setting
  .gitignore
  next.config.mjs
  package.json
  pnpm-lock.yaml
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/global-error.tsx
  src/instrumentation-client.ts
  src/instrumentation.ts
Labels: 🌐 Chore

#182 [BUGFIX] : 소셜 탭에 QR미리보기 뜨는 버그 수정
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
Labels: 🐛 BugFix, 🫠 지수

#189 [DEPLOY] #188 sentry 포함 프로덕션 배포 #188
  .gitignore
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/assets1.png
  public/assets2.png
  public/main-image.png
  public/main-logo-black.png
  public/main/1.gif
  public/main/2.gif
  public/main/3.gif
  public/main/4.gif
  public/main/main-bg.png
  public/main/section1-main.png
  public/main/section3-1.png
  public/main/section3-2.png
  public/main/section3-5.png
  public/main/simple2-1.png
  public/main/simple2-2.png
  public/main/simple2-3.png
  public/section35.png
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/global-error.tsx
  src/components/card/flip-card.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/main/section-four.tsx
  src/components/main/section-half.tsx
  src/components/main/section-one.tsx
  src/components/main/section-three.tsx
  src/components/main/section-two.tsx
  src/instrumentation-client.ts
  src/instrumentation.ts
Labels: 🐳 미경, 🛸 Deploy

#196 [FEAT]#186 메인 페이지 이미지 수정 및 스크롤 탑 버튼 생성
  public/maincard/1.jpg
  public/maincard/1.svg
  public/maincard/2.jpg
  public/maincard/2.svg
  public/maincard/3.jpg
  public/maincard/3.svg
  public/maincard/4.jpg
  public/maincard/4.svg
  public/maincard/5.jpg
  public/maincard/5.svg
  public/maincard/6.jpg
  public/maincard/6.svg
  public/maincard/7.jpg
  public/maincard/7.svg
  public/maincard/8.jpg
  public/maincard/8.svg
  public/maincard/9.jpg
  public/maincard/9.svg
  src/app/page.tsx
  src/components/main/ScrollToTopButton.tsx
  src/components/main/section-five.tsx
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#192 [FEAT]#180 404 에러 페이지 추가
  src/app/[...slug]/page.client.tsx
  src/app/[...slug]/page.tsx
  src/app/card/[...id]/page.tsx
  src/app/not-found.tsx
  src/components/icons/error-page-icon.tsx
Labels: ✨Feature, 🌸 수민

#191 [BUGFIX] #190 redirect bug
  src/middleware.ts
  src/utils/supabase/middleware.ts
Labels: 🐛 BugFix, 🫠 지수

#203 [FEAT]#183 Editor Header
  public/icons/logo_blue.svg
  public/icons/logo_white.svg
  src/app/editor/layout.tsx
  src/components/icons/save-icon.tsx
  src/components/layouts/editor-header.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/components/layouts/nav-bar.tsx
Labels: ✨Feature, 💄 Html&css, 🫠 지수

#198 [FEAT] #195 명함 생성 제한
  src/apis/card-interaction.ts
  src/components/dashboard/create-new-card.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
Labels: ✨Feature, 🐳 미경

#207 [FEAT]#194 스포이드 기능 개선 및 html2canvas 추가
  package.json
  pnpm-lock.yaml
  src/components/editor/elements/backgrounds/color-picker.tsx
Labels: ✨Feature, 🌸 수민

#210 [BUGFIX] 명함 삭제 알럿창의 버튼 스타일 적용 오류 수정
  tailwind.config.ts
Labels: 🐛 BugFix, 🌸 수민

#200 [FEAT] #160 공유된 페이지 유입경로 체크 및 통계
  public/icons/logo_blue.svg
  public/icons/logo_white.svg
  src/apis/weekly-source-count.api.ts
  src/app/[...slug]/page.client.tsx
  src/components/card-detail/path-analysis-chart.tsx
  src/components/chart/stacked-chart-wrapper.tsx
  src/components/chart/stacked-chart.tsx
  src/components/dashboard/card-item.tsx
  src/constants/query-key.ts
  src/hooks/queries/use-source-count.ts
  src/utils/card-detail/week-in-month.util.ts
Labels: ✨Feature, 🐳 미경

#211 [REFACTOR] #202 내명함 페이지 명함 불러오기 및 삭제하기 즉시 반영
  src/apis/dashboard.api.ts
  src/app/dashboard/my-cards/page.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/dashboard/card-item.tsx
  src/components/dashboard/card-list.tsx
  src/constants/query-key.ts
  src/hooks/mutations/use-mycard-delete.ts
  src/hooks/queries/use-card-list.ts
Labels: ♻️ Refactor, 🐳 미경

#212 [REFACTOR]#204 템플릿 가로 세로 고정
  src/components/editor/elements/templates/templates-sidebar.tsx
  src/components/template-list/template-card.tsx
  src/store/editor.store.ts
  src/types/editor.type.ts
  src/types/supabase.ts
  src/utils/editor/editor-card-type-guard.ts
  src/utils/editor/warn-sweet-alert.ts
Labels: ✨Feature, ♻️ Refactor, 🫠 지수

#216 [CHORE] #215 프로덕션 배포 전 next.config.mjs 수정
  .eslintrc.json
  next.config.mjs
Labels: 🌐 Chore, 🐳 미경

#224 [FEAT]/#199 에디터 저장로직 수정 및 에디터 리펙토링
  src/apis/card-save.ts
  src/apis/check-slug-exists.ts
  src/apis/upload-to-storage.ts
  src/components/editor/canvas-elements-render.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/editor-ui/use-slugged-save-card.ts
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/store/editor.stage.store.ts
  src/store/editor.store.ts
  src/utils/editor/convert-dataurl-to-blob.ts
  src/utils/editor/editor-upload-stage-image.ts
  src/utils/editor/validate-slug.ts
Labels: 📬 API, ✨Feature, ♻️ Refactor, ❤️ 종욱

#220 [FEAT] #214 카드 미리보기
  src/components/editor/editor-ui/bottomTab/editor-bottom-tab.tsx
  src/components/editor/editor-ui/bottomTab/preview-stage.tsx
  src/components/editor/elements/images/preview-image-canvas.tsx
  src/components/editor/elements/qr-social/preview-qr-canvas.tsx
  src/components/editor/elements/qr-social/preview-social-canvas.tsx
  src/components/editor/elements/text/preview-text-canvas.tsx
  src/components/editor/elements/uploads/preview-upload-canvas.tsx
Labels: ✨Feature, ♻️ Refactor, 🫠 지수

#223 [BUGFIX] #221 회원가입 창에서만 유효성 검사 나오도록 수정
  src/components/auth/auth-form.tsx
Labels: 🐛 BugFix, 🫠 지수

#222 [BUGFIX] #219 Flip 버튼 에러
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/utils/editor/warn-sweet-alert.ts
Labels: ♻️ Refactor, 🐛 BugFix, 🫠 지수

#225 [FEAT] #206 로그인 후 있던 페이지로 redirect
  src/apis/auth-server.api.ts
  src/apis/common-server.api.ts
  src/apis/social-server.api.ts
  src/apis/user-client.api.ts
  src/apis/user-server.api.ts
  src/app/auth/callback/route.ts
  src/components/auth/auth-form.tsx
  src/components/layouts/editor-header.tsx
  src/components/layouts/header-auth-button.tsx
  src/components/layouts/header.tsx
  src/components/modals/auth/auth-signup.tsx
  src/utils/auth/auth-check.ts
  src/utils/auth/duplicate-validation.ts
Labels: 📬 API, ✨Feature, 🫠 지수

#229 [DEPLOY] #228 UT테스트 전 중간 배포
  src/apis/auth-server.api.ts
  src/apis/card-save.ts
  src/apis/check-slug-exists.ts
  src/apis/common-server.api.ts
  src/apis/social-server.api.ts
  src/apis/upload-to-storage.ts
  src/apis/user-client.api.ts
  src/apis/user-server.api.ts
  src/app/auth/callback/route.ts
  src/components/auth/auth-form.tsx
  src/components/editor/canvas-elements-render.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/bottomTab/editor-bottom-tab.tsx
  src/components/editor/editor-ui/bottomTab/preview-stage.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/editor-ui/use-slugged-save-card.ts
  src/components/editor/elements/images/preview-image-canvas.tsx
  src/components/editor/elements/qr-social/preview-qr-canvas.tsx
  src/components/editor/elements/qr-social/preview-social-canvas.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/text/preview-text-canvas.tsx
  src/components/editor/elements/uploads/preview-upload-canvas.tsx
  src/components/layouts/editor-header.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/components/layouts/header-auth-button.tsx
  src/components/layouts/header.tsx
  src/components/modals/auth/auth-signup.tsx
  src/store/editor.stage.store.ts
  src/store/editor.store.ts
  src/utils/auth/auth-check.ts
  src/utils/auth/duplicate-validation.ts
  src/utils/editor/convert-dataurl-to-blob.ts
  src/utils/editor/editor-upload-stage-image.ts
  src/utils/editor/validate-slug.ts
  src/utils/editor/warn-sweet-alert.ts
Labels: 🐳 미경, 🛸 Deploy

#233 BUGFIX] #230 뒷면 복사 및 이미지 저장
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/editor-ui/use-slugged-save-card.ts
  src/components/editor/elements/images/element-image-canvas.tsx
  src/utils/editor/wait-to-load.ts
Labels: 🐛 BugFix, ❤️ 종욱

#232 [BUGFIX] #231 로컬스토리지 유저 관련 버그 수정
  src/components/layouts/header-auth-button.tsx
  src/utils/auth/auth-check.ts
Labels: 🐛 BugFix

#239 [FEAT] #235 작업 내용 sessionStorage에 저장
  src/store/editor.store.ts
Labels: ✨Feature, 🫠 지수

#226 [FEAT]/#197 메인페이지 변경
  public/gif/chart-manual.gif
  public/gif/editor-manual.gif
  public/gif/share-manual.gif
  public/gif/template-manual.gif
  public/logo-white.png
  public/main/ex-card-1.png
  public/main/ex-card-2.png
  public/main/ex-card-3.png
  public/main/half-bg-img.png
  public/main/main-card-img.png
  public/main/share-img.png
  public/main/statistics-img.png
  src/app/page.tsx
  src/components/main/main-Intor-section.tsx
  src/components/main/main-feature-section.tsx
  src/components/main/main-how-it-works-section.tsx
  src/components/main/main-last-section.tsx
  src/components/main/main-promotion-section.tsx
  src/components/main/main-tip-section.tsx
  src/components/main/section-five.tsx
Labels: ♻️ Refactor, ❤️ 종욱

#241 [FEAT]#240 #242 저장 초기화 및 문제 해결
  src/components/editor/editor-ui/use-slugged-save-card.ts
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/store/editor.store.ts
  src/utils/editor/convert-dataurl-to-blob.ts
  src/utils/editor/editor-reset-state.ts
  src/utils/editor/editor-upload-stage-image.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#244 [BUGFIX] #243 Image url fix
  src/apis/card-delete.ts
  src/apis/common-server.api.ts
  src/apis/upload-to-storage.ts
  src/components/card-detail/left-nav-section.tsx
  src/components/card/save-share-modal.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/dashboard/card-item.tsx
  src/constants/card-image.ts
  src/hooks/mutations/use-card-delete.ts
  src/hooks/mutations/use-mycard-delete.ts
  src/hooks/queries/use-slug-url.ts
Labels: 🐛 BugFix, 🫠 지수

#246 [STYLE]#236 상세/공유된 페이지 세로 명함 UI 반영
  src/components/card/flip-card.tsx
  src/components/card/konva-stage-viewer.tsx
  src/components/icons/flip-arrow.tsx
Labels: 💄 Html&css, 🌸 수민

#247 [FEAT] #218 qr 코드 저장
  src/components/card/save-share-modal.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/constants/url.constant.ts
  src/utils/interaction/download-from-canvas.ts
Labels: ✨Feature, 🐳 미경

#250 [BUGFIX] #249 닉네임 중복 시 회원가입 가능한 버그 수정
  src/components/auth/auth-form.tsx
Labels: 🐛 BugFix, 🫠 지수

#251 [DEPLOY] #245 중간 배포 확인
  public/gif/chart-manual.gif
  public/gif/editor-manual.gif
  public/gif/share-manual.gif
  public/gif/template-manual.gif
  public/logo-white.png
  public/main/ex-card-1.png
  public/main/ex-card-2.png
  public/main/ex-card-3.png
  public/main/half-bg-img.png
  public/main/main-card-img.png
  public/main/share-img.png
  public/main/statistics-img.png
  src/apis/card-delete.ts
  src/apis/common-server.api.ts
  src/apis/upload-to-storage.ts
  src/app/page.tsx
  src/components/auth/auth-form.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/card/flip-card.tsx
  src/components/card/konva-stage-viewer.tsx
  src/components/card/save-share-modal.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/dashboard/card-item.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/editor-ui/use-slugged-save-card.ts
  src/components/editor/elements/images/element-image-canvas.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/components/icons/flip-arrow.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/components/layouts/header-auth-button.tsx
  src/components/main/main-Intor-section.tsx
  src/components/main/main-feature-section.tsx
  src/components/main/main-how-it-works-section.tsx
  src/components/main/main-last-section.tsx
  src/components/main/main-promotion-section.tsx
  src/components/main/main-tip-section.tsx
  src/components/main/section-five.tsx
  src/constants/card-image.ts
  src/constants/url.constant.ts
  src/hooks/mutations/use-card-delete.ts
  src/hooks/mutations/use-mycard-delete.ts
  src/hooks/queries/use-slug-url.ts
  src/store/editor.store.ts
  src/utils/auth/auth-check.ts
  src/utils/editor/convert-dataurl-to-blob.ts
  src/utils/editor/editor-reset-state.ts
  src/utils/editor/editor-upload-stage-image.ts
  src/utils/editor/wait-to-load.ts
  src/utils/interaction/download-from-canvas.ts
Labels: 🐳 미경, 🛸 Deploy

#260 [REFACTOR]#201 텍스트 편집시 엔터 없이도 저장 및 바깥 영역 클릭시 선택 해제
  src/app/editor/page.tsx
  src/components/editor/editor-container.tsx
Labels: ♻️ Refactor, ❤️ 종욱

#256 [FEAT]#234 저장 및 공유 모달 기존 로직 변경 및 공통 모달 수정
  src/app/dashboard/my-cards/page.tsx
  src/app/layout.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/card/save-share-modal.tsx
  src/components/common/common-modal.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/dashboard/card-item.tsx
  src/store/common-modal.store.ts
  src/store/save-share-modal.store.ts
Labels: ♻️ Refactor, 🌸 수민

#258 [BUG FIX] #255 내명함페이지 가장 높은 조회수
  src/apis/monthly-chart.api.ts
  src/components/dashboard/monthly-chart.tsx
  src/components/dashboard/most-view-card.tsx
  src/hooks/mutations/use-mycard-delete.ts
  src/hooks/queries/use-card-list.ts
  src/hooks/queries/use-month-chart.ts
Labels: 🐛 BugFix, 🐳 미경

#253 [FEAT]#248 metadata og 태그 추가
  public/favicon.png
  public/main-og.png
  src/app/layout.tsx
Labels: ✨Feature, 🌸 수민

#263 [FEAT]#262 기능 활성화 이전 안내 문구 창 추가
  src/app/[...slug]/page.client.tsx
  src/components/card-detail/export-buttons.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/dashboard/card-edit-dropdown.tsx
Labels: ✨Feature, 🌸 수민

#254 [REFACTOR]/#252 에디터 배포시 생긴 문제 수정
  src/components/auth/auth-form.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/constants/url.constant.ts
  src/hooks/use-slugged-save-card.ts
  src/types/editor.type.ts
  src/utils/auth/auth-validate-schema.ts
  src/utils/editor/create-card-insert-payload.ts
  src/utils/editor/editor-validate-schema.ts
  src/utils/editor/get-State-Image-urls.ts
  src/utils/editor/validate-slug.ts
Labels: ♻️ Refactor, ❤️ 종욱

#259 [FEAT]/#227 편집하기 클릭 시 캔버스로 이동
  src/app/editor/page.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/editor/elements/uploads/element-upload-canvas.tsx
Labels: ✨Feature, ❤️ 종욱

#261 [FEAT]#257 공유된 명함 페이지 및 상세 페이지 명함 이미지 다운로드
  src/apis/card-interaction.ts
  src/apis/card-save.ts
  src/apis/card-select-list.ts
  src/apis/card-view.api.ts
  src/apis/get-slug-data.ts
  src/apis/interaction-line-chart.api.ts
  src/apis/interaction.ts
  src/apis/storage.ts
  src/apis/user-click-donut-chart.api.ts
  src/app/[...slug]/page.client.tsx
  src/app/api/log-exit/route.ts
  src/components/card/flip-card.tsx
  src/components/card/konva-stage-viewer.tsx
  src/components/card/save-share-modal.tsx
  src/hooks/mutations/use-init-session.ts
  src/utils/editor/editor-data-url-to-blob.ts
Labels: ✨Feature, 🌸 수민

#266 [FEAT] #264 계정 설정 및 조회기능 비활성화
  src/app/dashboard/account/page.tsx
  src/components/dashboard/sort-dropdown.tsx
Labels: ✨Feature, 🐳 미경

#267 [FEAT]/#268 미완료된 기능들은 준비중 알림 띄우기
  src/app/[...slug]/page.client.tsx
  src/components/card-detail/export-buttons.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/editor/elements/diagrams/elements-diagrams.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/templates/templates-sidebar.tsx
  src/components/editor/elements/text/text-style-sidebar.tsx
  src/utils/common/sweet-coming-soon-alert.ts
Labels: ✨Feature, ❤️ 종욱

#265 [FEAT] #44 요소 순서 설정 속성 추가
  src/components/card/konva-stage-viewer.tsx
  src/components/editor/canvas-elements-render.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/elements/images/element-image-canvas.tsx
  src/components/editor/elements/qr-social/element-qr-canvas.tsx
  src/components/editor/elements/qr-social/element-social-canvas.tsx
  src/components/editor/elements/text/element-text-canvas.tsx
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/components/icons/editor/toolbar-move-bottom.tsx
  src/components/icons/editor/toolbar-move-down.tsx
  src/components/icons/editor/toolbar-move-top.tsx
  src/components/icons/editor/toolbar-move-up.tsx
  src/store/editor.store.ts
Labels: ✨Feature, 🫠 지수

#271 [FEAT] #205 내 명함, 템플릿 으로 들어올 때 가로세로 모달 제거
  src/app/editor/page.tsx
  src/components/dashboard/card-item.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/modal/editor-vt-hr-select-modal.tsx
  src/hooks/queries/use-template-single.ts
Labels: ✨Feature, 🫠 지수

#272 [DEPLOY] UT 테스트용 프로덕션 배포 #269
  src/app/editor/page.tsx
  src/components/dashboard/card-item.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/modal/editor-vt-hr-select-modal.tsx
  src/hooks/queries/use-template-single.ts
Labels: 🐳 미경, 🛸 Deploy

#274 [BUG FIX] #273 소셜 미리보기 변수 수정
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
Labels: 🐛 BugFix, 🫠 지수

#276 [BUGFIX]/#275 에디터 버그수정 (UT 반영)
  src/apis/get-public-url-from-storage.ts
  src/components/editor/canvas-elements-render.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/text/text-edit-content.tsx
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/constants/editor.constant.ts
  src/hooks/use-slugged-save-card.ts
  src/types/unsplash.ts
  src/utils/editor/save/create-card-insert-payload.ts
  src/utils/editor/save/get-state-image-url.ts
  src/utils/editor/save/validate-slug.ts
Labels: 🐛 BugFix, ❤️ 종욱

#279 [BUGFIX] #277 템플릿, 내 명함으로 들어왔을 때 작업내용 증발되는 상황
  src/app/editor/page.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/components/template-list/template-card.tsx
  src/hooks/queries/use-template-single.ts
  src/types/supabase.ts
  src/types/templates.type.ts
Labels: ♻️ Refactor, 🐛 BugFix, 🫠 지수

#286 [BUGFIX]#283 이미지 파일 업로드 시 publicUrl까지 함께 반환하도록 수정
  src/apis/get-public-url-from-storage.ts
  src/apis/storage.ts
  src/components/editor/elements/uploads/uploads-sidebar.tsx
Labels: 🐛 BugFix, 🌸 수민

#287 [BUGFIX] #285 세션스토리지 버그 픽스
  src/app/editor/page.tsx
Labels: 🐛 BugFix, 🫠 지수

#293 [DEPLOY] #284 UT개선 사항 반영
  src/apis/storage.ts
  src/app/editor/page.tsx
  src/components/editor/canvas-elements-render.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/text/text-edit-content.tsx
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/components/template-list/template-card.tsx
  src/constants/editor.constant.ts
  src/hooks/queries/use-template-single.ts
  src/hooks/use-slugged-save-card.ts
  src/types/supabase.ts
  src/types/templates.type.ts
  src/types/unsplash.ts
  src/utils/editor/save/create-card-insert-payload.ts
  src/utils/editor/save/get-state-image-url.ts
  src/utils/editor/save/validate-slug.ts
Labels: 🐳 미경, 🛸 Deploy

#295 [BUGFIX]#294 명함 삭제 후 리다이렉션 시 최신 데이터가 반영되지 않는 문제 수정
  src/components/card-detail/left-nav-section.tsx
  src/hooks/mutations/use-mycard-delete.ts
  src/hooks/queries/use-card-select-list.ts
Labels: 🐛 BugFix, 🌸 수민

#298 Feat/#281 에디터 저장 편집시 기존 업데이트
  src/apis/card-update.ts
  src/apis/common-client.api.ts
  src/app/editor/page.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/constants/query-key.ts
  src/hooks/mutations/use-card-update.ts
  src/hooks/queries/use-card-by-id-single.ts
  src/hooks/use-slugged-save-card.ts
  src/utils/editor/save/create-card-update-payload.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#310 [REFACTOR] : useCardSlug도 리패치 항상 하도록 #303
  src/hooks/queries/use-card-slug.ts
  src/hooks/use-slugged-save-card.ts
Labels: ♻️ Refactor, ❤️ 종욱

#313 [FEAT]#312 업로드 된 이미지 삭제 시 대체 이미지 표시 및 리페치 추가
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/hooks/queries/use-card-by-id-single.ts
Labels: ✨Feature, 🐛 BugFix, 🌸 수민

#314 [DEPLOY] #311 버그 수정 후 프로덕션 배포
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/hooks/queries/use-card-by-id-single.ts
  src/hooks/queries/use-card-slug.ts
  src/hooks/use-slugged-save-card.ts
Labels: 🐛 BugFix, 🐳 미경, 🛸 Deploy

#317 ♻️ refactor : unsplash 승인을 받기 위해 코드 수정 #316
  src/components/editor/elements/images/images-sidebar.tsx
  src/types/unsplash.ts
Labels: ♻️ Refactor, ❤️ 종욱

#319 [DEPLOY] #318 unsplash 승인용 배포
  src/components/editor/elements/images/images-sidebar.tsx
  src/types/unsplash.ts
Labels: 🐳 미경, 🛸 Deploy

#320 Feat/#315 zindex 실제 배열로 반환하도록 변경
  src/components/card/konva-stage-viewer.tsx
  src/components/editor/canvas-elements-render.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/elements/images/element-image-canvas.tsx
  src/components/editor/elements/qr-social/element-qr-canvas.tsx
  src/components/editor/elements/qr-social/element-social-canvas.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/templates/templates-sidebar.tsx
  src/components/editor/elements/text/element-text-canvas.tsx
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/constants/editor.constant.ts
  src/store/editor.store.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#325 [FEAT]/#201 구글 폰트 적용 및 텍스트 속성 변경
  package.json
  pnpm-lock.yaml
  src/app/api/google-font/route.ts
  src/components/editor/editor-ui/color-picker.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/elements/backgrounds/background-sidebar.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/text/element-text-canvas.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/text/text-style-sidebar.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/components/ui/popover.tsx
  src/constants/editor.constant.ts
  src/types/editor.type.ts
Labels: 📬 API, ✨Feature, ♻️ Refactor, ❤️ 종욱

#322 [FEAT] #321 로딩스피너 추가
  src/app/editor/page.tsx
  src/app/loading.tsx
  src/components/common/loading-spinner.tsx
Labels: ✨Feature, 🐳 미경

#301 [STYLE]#292 공유된 명함 페이지 마크업
  src/app/[...slug]/page.client.tsx
  src/components/card/card-skeleton.tsx
  src/components/card/flip-card.tsx
  src/components/card/konva-stage-viewer.tsx
  src/components/icons/left-arrow.tsx
Labels: ✨Feature, 💄 Html&css, 🌸 수민

#328 [FEAT]/#290 에디터 텍스트 속성 분리 및 그림자 추가
  package.json
  pnpm-lock.yaml
  src/components/editor/elements/text/element-text-canvas.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/text/text-style-sidebar.tsx
  src/components/editor/elements/text/text-style/text-align-and-color.tsx
  src/components/editor/elements/text/text-style/text-shadow-selector.tsx
  src/components/editor/elements/text/text-style/text-style-options-and-size.tsx
  src/components/ui/accordion.tsx
  src/components/ui/slider.tsx
  src/constants/editor.constant.ts
  src/types/editor.type.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#297 [FEAT] #280 에디터 요소 UI
  src/components/editor/canvas-elements-render.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar.tsx
  src/components/editor/elements/diagrams/elements-diagrams.tsx
  src/components/editor/elements/element/ElementsCanvasElement.tsx
  src/components/editor/elements/element/element-sidebar.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/icons/editor/element/left-arrow.tsx
  src/components/icons/editor/element/left-circle.tsx
  src/components/icons/editor/element/left-dotted-arrow.tsx
  src/components/icons/editor/element/left-dotted-circle.tsx
  src/components/icons/editor/element/left-dotted2-arrow.tsx
  src/components/icons/editor/element/left-dotted2-circle.tsx
  src/components/icons/editor/element/left-right-arrow.tsx
  src/components/icons/editor/element/left-right-circle.tsx
  src/components/icons/editor/element/left-right-dotted-arrow.tsx
  src/components/icons/editor/element/left-right-dotted-circle.tsx
  src/components/icons/editor/element/left-right-dotted2-arrow.tsx
  src/components/icons/editor/element/left-right-dotted2-circle.tsx
  src/components/icons/editor/element/line-dotted-2.tsx
  src/components/icons/editor/element/line-dotted.tsx
  src/components/icons/editor/element/line.tsx
  src/components/icons/editor/element/right-arrow.tsx
  src/components/icons/editor/element/right-circle.tsx
  src/components/icons/editor/element/right-dotted-arrow.tsx
  src/components/icons/editor/element/right-dotted-circle.tsx
  src/components/icons/editor/element/right-dotted2-arrow.tsx
  src/components/icons/editor/element/right-dotted2-circle.tsx
  src/middleware.ts
  src/types/editor.type.ts
Labels: 💄 Html&css, 🐛 BugFix, 🫠 지수

#326 [STYLE] #324 내명함 페이지 반응형 마크업
  public/minichartm.svg
  src/app/dashboard/layout.tsx
  src/app/dashboard/my-cards/page.tsx
  src/components/dashboard/card-item.tsx
  src/components/dashboard/card-list.tsx
  src/components/dashboard/card-title-editor.tsx
  src/components/dashboard/create-new-card.tsx
  src/components/dashboard/monthly-chart.tsx
  src/components/dashboard/monthly-line-chart.tsx
  src/components/dashboard/most-view-card.tsx
  src/components/icons/add-icon.tsx
Labels: ♻️ Refactor, 💄 Html&css, 🐳 미경

#330 [FEAT]/#290 에디터 텍스트 속성 외곽선 및 투명도 / 저장 시 3개 제한 추가
  src/app/layout.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/editor-ui/text-style-selector/text-align-and-color.tsx
  src/components/editor/editor-ui/text-style-selector/text-opacity-selector.tsx
  src/components/editor/editor-ui/text-style-selector/text-shadow-selector.tsx
  src/components/editor/editor-ui/text-style-selector/text-stroke-selector.tsx
  src/components/editor/editor-ui/text-style-selector/text-style-options-and-size.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/text/element-text-canvas.tsx
  src/components/editor/elements/text/text-sidebar.tsx
  src/components/editor/elements/text/text-style-sidebar.tsx
  src/components/ui/accordion.tsx
  src/components/ui/slider.tsx
  src/constants/editor.constant.ts
  src/constants/url.constant.ts
  src/hooks/use-slugged-save-card.ts
  src/store/editor.sidebar.store.ts
  src/types/editor.type.ts
  src/utils/editor/editor-reset-state.ts
  src/utils/editor/save/validate-slug.ts
Labels: ✨Feature, ❤️ 종욱

#334 [STYLE] 템플릿 리스트 반응형 #331
  next.config.mjs
  src/app/template-list/layout.tsx
  src/components/template-list/tab-buttons.tsx
  src/components/template-list/template-card.tsx
  src/components/template-list/template-style-section.tsx
Labels: 🌐 Chore, 💄 Html&css, 🐳 미경

#336 [STYLE]#289 명함 상세 페이지 마크업
  src/app/card/[...id]/page.tsx
  src/components/card-detail/card-selector.tsx
  src/components/card-detail/export-buttons.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/card-detail/left-nav-skeleton-ui.tsx
  src/components/card-detail/path-analysis-chart.tsx
  src/components/card-detail/path-analysis-grid.tsx
  src/components/card-detail/stat-card-grid.tsx
  src/components/card-detail/stat-card.tsx
  src/components/card-detail/weekly-chart.tsx
  src/components/card/card-skeleton.tsx
  src/components/card/flip-card.tsx
  src/components/chart/chart-wrapper.tsx
  src/components/chart/donut-chart.tsx
  src/components/chart/line-chart.tsx
  src/components/chart/stacked-chart-wrapper.tsx
  src/components/chart/stacked-chart.tsx
  src/components/icons/card-detail/download-icon.tsx
  src/utils/statistics/calculate-total.ts
Labels: ♻️ Refactor, 💄 Html&css, 🌸 수민

#350 FEAT/#288 메인 페이지 UI (반응형 및 UI 요소 추가)
  package.json
  pnpm-lock.yaml
  public/main/half-bg-img.png
  public/main/main-promotion-img.jpg
  public/maincard/length/length-1.jpg
  public/maincard/length/length-2.jpg
  public/maincard/length/length-3.jpg
  public/maincard/length/length-4.jpg
  public/maincard/length/length-5.jpg
  public/maincard/length/length-6.jpg
  public/maincard/length/length-7.jpg
  src/app/api/google-font/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/main/ScrollToTopButton.tsx
  src/components/main/how-it-works-desktop.tsx
  src/components/main/how-it-works-mobile.tsx
  src/components/main/main-Intor-section.tsx
  src/components/main/main-feature-section.tsx
  src/components/main/main-footer.tsx
  src/components/main/main-how-it-works-section.tsx
  src/components/main/main-last-section.tsx
  src/components/main/main-promotion-section.tsx
  src/components/main/main-tip-section.tsx
  src/constants/env.constant.ts
  src/constants/main.constant.ts
  src/hooks/use-is-mobile.ts
  tailwind.config.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#341 [FEAT]#332 요소 추가
  src/components/card/konva-stage-viewer.tsx
  src/components/editor/canvas-elements-render.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/bottomTab/preview-stage.tsx
  src/components/editor/elements/element/ElementsCanvasElement.tsx
  src/components/editor/elements/element/element-sidebar.tsx
  src/components/editor/elements/element/preview-elements-canvas.tsx
  src/components/icons/editor/element/circle-dotted.tsx
  src/components/icons/editor/element/circle-white.tsx
  src/components/icons/editor/element/circle.tsx
  src/components/icons/editor/element/left-dotted-square.tsx
  src/components/icons/editor/element/left-dotted2-square.tsx
  src/components/icons/editor/element/left-right-dotted-square.tsx
  src/components/icons/editor/element/left-right-dotted2-circle.tsx
  src/components/icons/editor/element/left-right-dotted2-square.tsx
  src/components/icons/editor/element/left-right-square.tsx
  src/components/icons/editor/element/left-square.tsx
  src/components/icons/editor/element/right-dotted-square.tsx
  src/components/icons/editor/element/right-dotted2-square.tsx
  src/components/icons/editor/element/right-square.tsx
  src/components/icons/editor/element/square-dotted.tsx
  src/components/icons/editor/element/square-white.tsx
  src/components/icons/editor/element/square.tsx
  src/components/icons/editor/element/star-4.tsx
  src/components/icons/editor/element/star-5.tsx
  src/components/icons/editor/element/star-6.tsx
  src/components/icons/editor/element/star-8.tsx
  src/components/icons/editor/element/triangle-dotted.tsx
  src/components/icons/editor/element/triangle-white.tsx
  src/components/icons/editor/element/triangle.tsx
  src/constants/editor-elements.constant.ts
  src/constants/editor.constant.ts
  src/types/editor.type.ts
Labels: ✨Feature, 🫠 지수

#354 [FEAT]#346 상단 바 수정
  public/icons/business_card.svg
  src/components/common/tooltip.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
Labels: ✨Feature, 🫠 지수

#352 [FEAT]#339 bottom sheet 공통 컴포넌트 추가 및 명함 상세 반응형 bottom sheet추가
  src/app/card/[...id]/page.tsx
  src/app/layout.tsx
  src/components/card-detail/card-selector.tsx
  src/components/card-detail/left-nav-section.tsx
  src/components/card/save-share-modal.tsx
  src/components/chart/stacked-chart-wrapper.tsx
  src/components/chart/stacked-chart.tsx
  src/components/common/sheet-provider.tsx
  src/components/ui/sheet.tsx
  src/store/common-modal.store.ts
  src/store/sheet.store.ts
Labels: ✨Feature, 🌸 수민

#351 [FEAT]#343 초기화 버튼 클릭 시 안내창
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/utils/common/sweet-alert-util.ts
  src/utils/editor/editor-reset-alert.util.ts
Labels: ✨Feature, 🫠 지수

#355 [FEAT]#347 요소 삭제 키보드 이벤트
  src/app/editor/page.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/hooks/use-delete-key-press.ts
  src/hooks/use-redo-undo-press.ts
Labels: ✨Feature, ♻️ Refactor, 🫠 지수

#357 Feat/#353 에디터 unsplash 로직 변경 및 검색 재오픈 /main 카드 변경
  public/maincard/1.jpg
  public/maincard/2.jpg
  public/maincard/3.jpg
  public/maincard/4.jpg
  public/maincard/5.jpg
  public/maincard/6.jpg
  public/maincard/7.jpg
  public/maincard/8.jpg
  public/maincard/9.jpg
  public/maincard/length/length-1.jpg
  public/maincard/length/length-1.png
  public/maincard/length/length-2.jpg
  public/maincard/length/length-2.png
  public/maincard/length/length-3.jpg
  public/maincard/length/length-3.png
  public/maincard/length/length-4.jpg
  public/maincard/length/length-4.png
  public/maincard/length/length-5.jpg
  public/maincard/length/length-5.png
  public/maincard/length/length-6.jpg
  public/maincard/length/length-6.png
  public/maincard/length/length-7.jpg
  public/maincard/length/length-7.png
  src/app/api/unsplash/route.ts
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/main/main-Intor-section.tsx
  src/components/main/main-last-section.tsx
  src/constants/editor.constant.ts
  src/hooks/queries/use-unsplash-images.ts
  src/hooks/use-is-mobile.ts
  src/types/unsplash.ts
  tailwind.config.ts
Labels: ♻️ Refactor, ❤️ 종욱

#371 [DEPLOY] 최종 전 2차 프로덕션 배포 #370
  public/maincard/1.jpg
  public/maincard/2.jpg
  public/maincard/3.jpg
  public/maincard/4.jpg
  public/maincard/5.jpg
  public/maincard/6.jpg
  public/maincard/7.jpg
  public/maincard/8.jpg
  public/maincard/9.jpg
  public/maincard/length/length-1.jpg
  public/maincard/length/length-1.png
  public/maincard/length/length-2.jpg
  public/maincard/length/length-2.png
  public/maincard/length/length-3.jpg
  public/maincard/length/length-3.png
  public/maincard/length/length-4.jpg
  public/maincard/length/length-4.png
  public/maincard/length/length-5.jpg
  public/maincard/length/length-5.png
  public/maincard/length/length-6.jpg
  public/maincard/length/length-6.png
  public/maincard/length/length-7.jpg
  public/maincard/length/length-7.png
  src/app/api/unsplash/route.ts
  src/app/editor/page.tsx
  src/components/editor/editor-container.tsx
  src/components/editor/editor-ui/element-toolbar/editor-element-toolbar.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/main/main-Intor-section.tsx
  src/components/main/main-last-section.tsx
  src/constants/editor.constant.ts
  src/hooks/queries/use-unsplash-images.ts
  src/hooks/use-delete-key-press.ts
  src/hooks/use-is-mobile.ts
  src/hooks/use-redo-undo-press.ts
  src/types/unsplash.ts
  tailwind.config.ts
Labels: 🐳 미경

#374 [FEAT]#369 헤더 반응형
  src/app/page.tsx
  src/components/common/common-button.tsx
  src/components/layouts/nav-bar.tsx
  src/components/main/main-Intor-section.tsx
  src/components/main/main-footer.tsx
  src/components/ui/sheet.tsx
  tailwind.config.ts
Labels: ♻️ Refactor, ❤️ 종욱

#356 [REFACTOR] 명함 정렬 개선 #337
  src/apis/dashboard.client.api.ts
  src/components/dashboard/card-item.tsx
  src/components/dashboard/card-list.tsx
  src/components/dashboard/card-title-editor.tsx
  src/hooks/mutations/use-update-card-title.ts
  src/hooks/queries/use-card-list.ts
Labels: ♻️ Refactor, 🐳 미경

#365 [FEAT]#332 요소 속성
  public/icons/check.svg
  src/components/editor/editor-ui/element-style-selector/element-stroke-selector.tsx
  src/components/editor/editor-ui/sidebar/editor-sidebar-element.tsx
  src/components/editor/elements/element/ElementsCanvasElement.tsx
  src/components/editor/elements/element/element-sidebar.tsx
  src/components/editor/elements/element/element-style-sidebar.tsx
  src/components/icons/editor/element/line-dotted-2.tsx
  src/components/icons/editor/element/line-dotted.tsx
  src/components/icons/editor/element/line.tsx
  src/constants/editor-elements.constant.ts
  src/constants/editor.constant.ts
  src/types/editor.type.ts
  src/utils/common/same-array.util.ts
Labels: ✨Feature, 🫠 지수

#367 [FEAT] #349 로그인 회원가입 반응형, 자잘한 버그 수정
  public/icons/close.svg
  src/components/auth/auth-form.tsx
  src/components/editor/editor-ui/topbar/editor-topbar.tsx
  src/components/modals/auth/auth-modal.tsx
  src/utils/editor/editor-reset-alert.util.ts
  src/utils/editor/warn-sweet-alert.ts
Labels: ♻️ Refactor, 💄 Html&css, 🫠 지수

#372 [FEAT]#368 metadata
  src/apis/card-interaction.ts
  src/app/[...slug]/page.tsx
  src/app/card/[...id]/page.tsx
  src/app/dashboard/my-cards/page.tsx
  src/app/editor/layout.tsx
  src/app/layout.tsx
  src/app/template-list/layout.tsx
Labels: ✨Feature, 🫠 지수

#366 [FEAT] #329 반응형에 따른 버튼 분기처리
  src/app/[...slug]/page.client.tsx
  src/app/dashboard/my-cards/page.tsx
  src/components/dashboard/card-edit-dropdown.tsx
  src/components/dashboard/card-item.tsx
  src/components/dashboard/sort-dropdown.tsx
  src/components/ui/sheet.tsx
Labels: ♻️ Refactor, 💄 Html&css, 🐳 미경

#378 [FIX] : 헤더 반응형 브레이크포인트 md로 수정
  src/components/layouts/nav-bar.tsx
Labels: ♻️ Refactor, ❤️ 종욱

#375 [FEAT}/#358 에디터 모달 및 토스트 변경
  package.json
  pnpm-lock.yaml
  src/app/[...slug]/page.client.tsx
  src/app/editor/layout.tsx
  src/app/layout.tsx
  src/components/card-detail/export-buttons.tsx
  src/components/editor/editor-ui/color-picker.tsx
  src/components/editor/editor-ui/editor-input-alert.tsx
  src/components/editor/editor-ui/text-style-selector/text-align-and-color.tsx
  src/components/editor/elements/images/images-sidebar.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/editor/elements/templates/templates-sidebar.tsx
  src/components/editor/elements/text/text-style-sidebar.tsx
  src/components/editor/elements/uploads/element-upload-canvas.tsx
  src/components/editor/elements/uploads/uploads-sidebar.tsx
  src/components/layouts/editor-nav-bar.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-slugged-save-card.ts
  src/hooks/use-toast.ts
  src/lib/toast-util.ts
  src/store/editor.prompt-dialog.store.ts
  src/utils/common/sweet-coming-soon-alert.ts
  src/utils/editor/save/validate-slug.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#377 [FEAT]#340 카드 조회수 로직 수정
  src/apis/interaction.ts
  src/app/[...slug]/page.client.tsx
  src/components/card/flip-card.tsx
  src/components/card/save-share-modal.tsx
  src/constants/session.constant.ts
  src/hooks/mutations/use-init-session.ts
  src/hooks/use-interaction-tracker.ts
  src/utils/interaction/session-util.ts
Labels: ✨Feature, 🌸 수민

#393 [BUGFIX] #392 유입경로 차트 날짜 오류 픽스
  src/apis/monthly-chart.api.ts
  src/apis/weekly-source-count.api.ts
Labels: 🐛 BugFix, 🐳 미경

#388 [REFACTOR]/#381 메인페이지 UI변경 및 에디터 내부 UI 변경
  public/gif/chart-manual.gif
  public/gif/editor-manual.gif
  public/gif/share-manual.gif
  public/gif/template-manual.gif
  public/video/chart-manual.mp4
  public/video/editor-manual.mp4
  public/video/share-manual.mp4
  public/video/template-manual.mp4
  src/components/editor/editor-ui/text-style-selector/text-align-and-color.tsx
  src/components/editor/elements/qr-social/qrsocial-sidebar.tsx
  src/components/layouts/nav-bar.tsx
  src/components/main/how-it-works-desktop.tsx
  src/components/main/how-it-works-mobile.tsx
  src/components/main/main-footer.tsx
  src/components/main/main-last-section.tsx
  src/constants/editor.constant.ts
  src/constants/main.constant.ts
  src/lib/toast-util.ts
Labels: ♻️ Refactor, ❤️ 종욱

#396 [BUGFIX] #389 rotation 속성 추가
  src/components/editor/elements/element/ElementsCanvasElement.tsx
  src/components/editor/elements/element/element-sidebar.tsx
  src/types/editor.type.ts
Labels: 🐛 BugFix, 🫠 지수
