Repository lyra-j/uuno, pull requests merged in 2025-05, with the labels that each got.

#400 [FEAT] #376 깃 킵 삭제
  public/favicon.png
  public/fonts/GeistMonoVF.woff
  public/fonts/GeistVF.woff
  src/apis/interaction.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/providers/.gitkeep
  src/store/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
Labels: 🌐 Chore, 🐳 미경

#402 [FEAT]/#401 에디터 템플릿 수정
  src/components/editor/elements/templates/templates-sidebar.tsx
  src/utils/editor/warn-sweet-alert.ts
Labels: ✨Feature, ♻️ Refactor, ❤️ 종욱

#404 [BUGFIX]#399 명함 상세 및 공유된 명함 페이지 에러 해결
  src/apis/card-interaction.ts
  src/apis/card-select-list.ts
  src/apis/interaction.ts
  src/app/[...slug]/page.client.tsx
  src/app/card/[...id]/page.tsx
  src/components/card-detail/share-button.tsx
  src/hooks/mutations/use-init-session.ts
  src/hooks/mutations/use-mycard-delete.ts
  src/types/supabase.type.ts
Labels: 🐛 BugFix, 🌸 수민

#406 [DOCS] #384 리드미 수정
  README.md
Labels: 📃 Docs, 🐳 미경

#407 [DEPLOY] #403 최종전 프로덕션 배포
  README.md
  public/favicon.png
  public/fonts/GeistMonoVF.woff
  public/fonts/GeistVF.woff
  src/apis/card-interaction.ts
  src/apis/card-select-list.ts
  src/apis/interaction.ts
  src/app/[...slug]/page.client.tsx
  src/app/card/[...id]/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/.gitkeep
  src/components/card-detail/share-button.tsx
  src/components/editor/elements/templates/templates-sidebar.tsx
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/hooks/mutations/use-init-session.ts
  src/hooks/mutations/use-mycard-delete.ts
  src/providers/.gitkeep
  src/store/.gitkeep
  src/types/.gitkeep
  src/types/supabase.type.ts
  src/utils/.gitkeep
  src/utils/editor/warn-sweet-alert.ts
Labels: 🐳 미경, 🛸 Deploy

#408 [REFACTOR]#401 템플릿 초기화 로직 변경
  src/components/editor/elements/templates/templates-sidebar.tsx
Labels: 🐞 Bug, ♻️ Refactor, ❤️ 종욱

#410 [STYLE]#409 내 명함 상세 페이지 주간 차트 라벨 색상 및 세로 명함 영역 플립 아이콘 위치 재설정
  src/components/card-detail/weekly-chart.tsx
  src/components/card/flip-card.tsx
Labels: 💄 Html&css, 🌸 수민

#412 [REFACTOR]카드 삭제 후 정렬 쿼리 무효화 로직 추가 #411
  src/hooks/mutations/use-mycard-delete.ts
Labels: 🐛 BugFix, 🌸 수민

#413 [DEPLOY] #403 최종전 프로덕션 배포 #403
  src/components/card-detail/weekly-chart.tsx
  src/components/card/flip-card.tsx
  src/components/editor/elements/templates/templates-sidebar.tsx
  src/hooks/mutations/use-mycard-delete.ts
Labels: 🐳 미경, 🛸 Deploy

#415 [REFACTOR]#414 실시간 차트 반영 로직 추가
  src/hooks/queries/use-click-total-chart.ts
  src/hooks/queries/use-month-chart.ts
  src/hooks/queries/use-monthly-interaction-cnt.ts
  src/hooks/queries/use-source-count.ts
  src/hooks/queries/use-week-chart.ts
  src/hooks/use-interaction-tracker.ts
Labels: 🐛 BugFix, 🌸 수민

#416 [DEPLOY] #403 최종전 프로덕션 배포
  src/hooks/queries/use-click-total-chart.ts
  src/hooks/queries/use-month-chart.ts
  src/hooks/queries/use-monthly-interaction-cnt.ts
  src/hooks/queries/use-source-count.ts
  src/hooks/queries/use-week-chart.ts
  src/hooks/use-interaction-tracker.ts
Labels: 🐳 미경, 🛸 Deploy

#420 [BUGFIX] 방문자 클릭 분석 통계 로직 수정
  src/apis/interaction.ts
  src/app/[...slug]/page.client.tsx
  src/components/card/flip-card.tsx
  src/hooks/mutations/use-init-session.ts
  src/hooks/use-interaction-tracker.ts
Labels: 🐛 BugFix, 🌸 수민

#418 [REFACTOR]#417 초기화 변경
  src/hooks/mutations/use-update-card-title.ts
  src/hooks/queries/use-card-by-id-single.ts
Labels: ♻️ Refactor, ❤️ 종욱
